version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/filemanagement
      - JWT_SECRET=your_jwt_secret
      - GCLOUD_STORAGE_BUCKET=your_bucket_name
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
